### ISSUE TITLE
Bug: comtry apply command  fails because tmp storage doesn't exist

### ISSUE THREAD

**Issue by airtonix** [comtrya/comtrya#271] opened 2022-11-17 11:03 UTC
**Description**

```
PS C:\Users\zenobius> comtrya -d https://github.com/airtonix/dotfiles  apply
 INFO execute: Syncing Git repository https://github.com/airtonix/dotfiles to C:\Users\zenobius\AppData\Local\comtrya\manifests\git\githubcomairtonixdotfiles
ERROR execute: Failed to bootstrap repository, There was an error reported by git2-rs: failed to make directory 'C:\Users\zenobius\AppData\Local\comtrya\manifests\git\githubcomairtonixdotfiles': The system cannot find the path specified.
; class=Os (2)
ERROR execute: Failed to find manifests at https://github.com/airtonix/dotfiles
thread 'main' panicked at 'explicit panic', lib\src\manifests\mod.rs:53:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Steps to reproduce**
Step by step explanation. Please add the output of with `-vvv` flag enabled (be careful not to include any secrets from your config).

```
PS C:\Users\zenobius> comtrya -vv -d https://github.com/airtonix/dotfiles  apply
TRACE load_config{args=GlobalArgs { manifest_directory: Some("https://github.com/airtonix/dotfiles"), no_color: false, verbose: 2, command: Apply(Apply { manifests: [], 
dry_run: false }) }}:load_config: No Comtrya.yaml found in current working directory
TRACE load_config{args=GlobalArgs { manifest_directory: Some("https://github.com/airtonix/dotfiles"), no_color: false, verbose: 2, command: Apply(Apply { manifests: [], 
dry_run: false }) }}:load_config: No Comtrya.yaml found in users config directory
DEBUG build_contexts: context="user" key="id" value="0"
DEBUG build_contexts: context="user" key="name" value="zenobius"
DEBUG build_contexts: context="user" key="username" value="zenobius"
DEBUG build_contexts: context="user" key="home_dir" value="C:\\Users\\zenobius"
DEBUG build_contexts: context="user" key="config_dir" value="C:\\Users\\zenobius\\AppData\\Roaming"
DEBUG build_contexts: context="os" key="hostname" value="DESKTOP-EGEAD91"
DEBUG build_contexts: context="os" key="family" value="windows"
DEBUG build_contexts: context="os" key="name" value="windows"
DEBUG build_contexts: context="os" key="distribution" value="Windows"
DEBUG build_contexts: context="os" key="codename" value="unknown"
DEBUG build_contexts: context="os" key="bitness" value="64-bit"
DEBUG build_contexts: context="os" key="version" value="10.0.19042"
DEBUG build_contexts: context="os" key="edition" value="Windows 10 Home"
DEBUG build_contexts: context="env" key="ACSetupSvcPort" value="23210"
DEBUG build_contexts: context="env" key="ACSvcPort" value="17532"
DEBUG build_contexts: context="env" key="ALLUSERSPROFILE" value="C:\\ProgramData"
DEBUG build_contexts: context="env" key="APPDATA" value="C:\\Users\\zenobius\\AppData\\Roaming"
DEBUG build_contexts: context="env" key="CHROME_CRASHPAD_PIPE_NAME" value="\\\\.\\pipe\\crashpad_13760_GONIMJHSCLKOZBTY"
DEBUG build_contexts: context="env" key="CommonProgramFiles" value="C:\\Program Files\\Common Files"
DEBUG build_contexts: context="env" key="CommonProgramFiles(x86)" value="C:\\Program Files (x86)\\Common Files"
DEBUG build_contexts: context="env" key="CommonProgramW6432" value="C:\\Program Files\\Common Files"
DEBUG build_contexts: context="env" key="COMPUTERNAME" value="DESKTOP-EGEAD91"
DEBUG build_contexts: context="env" key="ComSpec" value="C:\\WINDOWS\\system32\\cmd.exe"
DEBUG build_contexts: context="env" key="DriverData" value="C:\\Windows\\System32\\Drivers\\DriverData"
DEBUG build_contexts: context="env" key="FPS_BROWSER_APP_PROFILE_STRING" value="Internet Explorer"
DEBUG build_contexts: context="env" key="FPS_BROWSER_USER_PROFILE_STRING" value="Default"
DEBUG build_contexts: context="env" key="GIT_INSTALL_ROOT" value="C:\\Users\\zenobius\\scoop\\apps\\git\\current"
DEBUG build_contexts: context="env" key="HOMEDRIVE" value="C:"
DEBUG build_contexts: context="env" key="HOMEPATH" value="\\Users\\zenobius"
DEBUG build_contexts: context="env" key="LOCALAPPDATA" value="C:\\Users\\zenobius\\AppData\\Local"
DEBUG build_contexts: context="env" key="LOGONSERVER" value="\\\\DESKTOP-EGEAD91"
DEBUG build_contexts: context="env" key="NUMBER_OF_PROCESSORS" value="16"
DEBUG build_contexts: context="env" key="OneDrive" value="C:\\Users\\zenobius\\OneDrive"
DEBUG build_contexts: context="env" key="ORIGINAL_XDG_CURRENT_DESKTOP" value="undefined"
DEBUG build_contexts: context="env" key="OS" value="Windows_NT"
DEBUG build_contexts: context="env" key="Path" value="C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\dotnet\\;C:\\Users\\zenobius\\scoop\\apps\\vscode\\current\\bin;C:\\Users\\zenobius\\scoop\\shims;C:\\Users\\zenobius\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\zenobius\\.comtrya"
DEBUG build_contexts: context="env" key="PATHEXT" value=".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL"
DEBUG build_contexts: context="env" key="PROCESSOR_ARCHITECTURE" value="AMD64"
DEBUG build_contexts: context="env" key="PROCESSOR_IDENTIFIER" value="AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD"
DEBUG build_contexts: context="env" key="PROCESSOR_LEVEL" value="25"
DEBUG build_contexts: context="env" key="PROCESSOR_REVISION" value="2102"
DEBUG build_contexts: context="env" key="ProgramData" value="C:\\ProgramData"
DEBUG build_contexts: context="env" key="ProgramFiles" value="C:\\Program Files"
DEBUG build_contexts: context="env" key="ProgramFiles(x86)" value="C:\\Program Files (x86)"
DEBUG build_contexts: context="env" key="ProgramW6432" value="C:\\Program Files"
DEBUG build_contexts: context="env" key="PSModulePath" value="C:\\Users\\zenobius\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules"
DEBUG build_contexts: context="env" key="PUBLIC" value="C:\\Users\\Public"
DEBUG build_contexts: context="env" key="RlsSvcPort" value="22112"
DEBUG build_contexts: context="env" key="SESSIONNAME" value="Console"
DEBUG build_contexts: context="env" key="SystemDrive" value="C:"
DEBUG build_contexts: context="env" key="SystemRoot" value="C:\\WINDOWS"
DEBUG build_contexts: context="env" key="TEMP" value="C:\\Users\\zenobius\\AppData\\Local\\Temp"
DEBUG build_contexts: context="env" key="TMP" value="C:\\Users\\zenobius\\AppData\\Local\\Temp"
DEBUG build_contexts: context="env" key="USERDOMAIN" value="DESKTOP-EGEAD91"
DEBUG build_contexts: context="env" key="USERDOMAIN_ROAMINGPROFILE" value="DESKTOP-EGEAD91" 
DEBUG build_contexts: context="env" key="USERNAME" value="zenobius"
DEBUG build_contexts: context="env" key="USERPROFILE" value="C:\\Users\\zenobius"
DEBUG build_contexts: context="env" key="windir" value="C:\\WINDOWS"
DEBUG build_contexts: context="env" key="TERM_PROGRAM" value="vscode"
DEBUG build_contexts: context="env" key="TERM_PROGRAM_VERSION" value="1.73.1"
DEBUG build_contexts: context="env" key="LANG" value="en_US.UTF-8"
DEBUG build_contexts: context="env" key="COLORTERM" value="truecolor"
DEBUG build_contexts: context="env" key="GIT_ASKPASS" value="c:\\Users\\zenobius\\scoop\\apps\\vscode\\1.73.1\\resources\\app\\extensions\\git\\dist\\askpass.sh"        
DEBUG build_contexts: context="env" key="VSCODE_GIT_ASKPASS_NODE" value="C:\\Users\\zenobius\\scoop\\apps\\vscode\\current\\Code.exe"
DEBUG build_contexts: context="env" key="VSCODE_GIT_ASKPASS_EXTRA_ARGS" value="--ms-enable-electron-run-as-node"
DEBUG build_contexts: context="env" key="VSCODE_GIT_ASKPASS_MAIN" value="c:\\Users\\zenobius\\scoop\\apps\\vscode\\1.73.1\\resources\\app\\extensions\\git\\dist\\askpass-main.js"
DEBUG build_contexts: context="env" key="VSCODE_GIT_IPC_HANDLE" value="\\\\.\\pipe\\vscode-git-1f217aff15-sock"
 INFO execute: Syncing Git repository https://github.com/airtonix/dotfiles to C:\Users\zenobius\AppData\Local\comtrya\manifests\git\githubcomairtonixdotfiles
ERROR execute: Failed to bootstrap repository, There was an error reported by git2-rs: failed to make directory 'C:\Users\zenobius\AppData\Local\comtrya\manifests\git\githubcomairtonixdotfiles': The system cannot find the path specified.
; class=Os (2)
ERROR execute: Failed to find manifests at https://github.com/airtonix/dotfiles
thread 'main' panicked at 'explicit panic', lib\src\manifests\mod.rs:53:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behaviour**
What the expected behaviour in your opinion.

> it shouldn't error

**Environment**
```
PS C:\Users\zenobius> (Invoke-WebRequest "https://raw.githubusercontent.com/kiedtl/winfetch/master/winfetch.ps1" -UseBasicParsing).Content.Remove(0,1) | Invoke-Expression
Missing config: Saved default config to 'C:\Users\zenobius\.config\winfetch\config.ps1'.

                     ....,,:;+ccllll  zenobius@DESKTOP-EGEAD91    
       ...,,+:;  cllllllllllllllllll  ------------------------    
 ,cclllllllllll  lllllllllllllllllll  OS: Windows 10 Home [64-bit]
 llllllllllllll  lllllllllllllllllll  Host: ASUS System Product Name
 llllllllllllll  lllllllllllllllllll  Kernel: 10.0.19042.0
 llllllllllllll  lllllllllllllllllll  Motherboard: ASUSTeK COMPUTER INC. ROG STRIX B550-I GAMING
 llllllllllllll  lllllllllllllllllll  Uptime: 6 hours 29 minutes
 llllllllllllll  lllllllllllllllllll  Packages: 4 (scoop)
                                      Shell: PowerShell v5.1.19041.1682
 llllllllllllll  lllllllllllllllllll  Resolution: 3440x1440, 3440x1440 
 llllllllllllll  lllllllllllllllllll  Terminal: Visual Studio Code
 llllllllllllll  lllllllllllllllllll  CPU: AMD Ryzen 7 5800X3D 8-Core Processor @ 3.4GHz
 llllllllllllll  lllllllllllllllllll  GPU: NVIDIA GeForce RTX 3090 Ti   
 llllllllllllll  lllllllllllllllllll  Memory: 7.57 GiB / 63.92 GiB (11%)
 `'ccllllllllll  lllllllllllllllllll  Disk (C:): 261 GiB / 930 GiB (28%)
       `' \\*::  :ccllllllllllllllll
                        ````''*::cll                          
                                  ``                          
PS C:\Users\zenobius> comtrya --help
comtrya 0.8.0

USAGE:
    comtrya.exe [FLAGS] [OPTIONS] <SUBCOMMAND>

FLAGS:
    -h, --help        Prints help information
        --no-color    Disable color printing
    -V, --version     Prints version information
    -v, --verbose     Debug & tracing mode (-v, -vv)

OPTIONS:
    -d, --manifest-directory <manifest-directory>    Directory

SUBCOMMANDS:
    apply
    help       Prints this message or the help of the given subcommand(s)
    version    
```

**Additional information**
Add more context which didn't fit in the fields above.

**Comment by icepuma** [comment] 2022-11-30 20:49
This sounds like https://github.com/libgit2/libgit2/issues/5241

**Comment by rawkode** [comment] 2023-01-04 21:49
I'm hoping a fix in gitsync should fix this. We'll upgrade and see what happens:

https://github.com/rawkode/gitsync/commit/929e31a9f5fd6cfc024365816e1b65634dddf0ea

**Comment by rawkode** [comment] 2023-01-04 21:59
#299

**Comment by rawkode** [comment] 2023-12-29 23:19
@airtonix Was this fixed?

**Comment by martintc** [comment] 2024-08-22 23:20
Not sure if this is confirmed as being caused by libgit2 or if it has been fixed. So What I will do is go through and make sure we don't have any hard dependencies on `/tmp` or if we do, provide a windows equivalent location.

**Comment by martintc** [comment] 2024-08-27 21:08
Could we just use conditional compilation and on windows builds utilize `%TEMP` instead of `/tmp`. Would like input from someone intimately familiar with windows.

https://stackoverflow.com/questions/15111103/tmp-folder-in-windows-like-tmp-in-linux

**Comment by martintc** [comment] 2024-09-23 03:27
Just did a run through and did not see any more locations where `/tmp` is hard coded outside of tests or for linux specific bits of code (for instance, the yay package provider). Will close this issue.

**Closed by martintc** 2024-09-23 03:27 UTC
Labels: Type::Defect
